const mascotas = [
  {
    id: 1,
    nombre: "Bigotes",
    especie: "Gato",
    raza: "Atigrado",
    edad: "3 años",
    tamanio: "Mediano",
    genero: "Macho",
    salud: ["Vacunado", "Castrado", "Desparasitado"],
    personalidad: ["Tranquilo", "Sociable"],
    apto: ["Indoor", "Apto niños"],
    descripcion:
      "Bigotes es un gato muy compañero que ama dormir sobre la cama y ronronear cuando lo acarician. Es tranquilo y se adapta fácil a cualquier hogar.",
    perfilAdoptante:
      "Buscamos una familia tranquila que pase tiempo en casa y quiera un compañero cariñoso para el día a día.",
    tipo: "Adopción",
    publicadoPor: "Ana Martínez",
    imagen: "Bigotes.jpg",
  },
  {
    id: 2,
    nombre: "Canela",
    especie: "Conejo",
    raza: "Mini lop",
    edad: "1 año",
    tamanio: "Pequeño",
    genero: "Hembra",
    salud: ["Desparasitada"],
    personalidad: ["Tímida", "Tranquila"],
    apto: ["Indoor", "Apto niños"],
    descripcion:
      "Canela es una coneja dulce y curiosa. Le encanta comer zanahoria y esconderse en su casita de cartón. Con paciencia se vuelve muy cariñosa.",
    perfilAdoptante:
      "Buscamos un hogar con espacio para que pueda saltar libre y alguien que sepa cuidar conejos.",
    tipo: "Adopción",
    publicadoPor: "Sofía Ramírez",
    imagen: "canela.jpg",
  },
  {
    id: 3,
    nombre: "Kira",
    especie: "Perro",
    raza: "Border Collie",
    edad: "3 años",
    tamanio: "Mediano",
    genero: "Hembra",
    salud: ["Vacunada", "Esterilizada", "Desparasitada"],
    personalidad: ["Activa", "Juguetona", "Sociable"],
    apto: ["Apto niños", "Outdoor"],
    descripcion:
      "Kira es una perra muy inteligente y llena de energía. Aprende trucos rápido y no para de correr atrás de la pelota. Necesita mucha actividad todos los días.",
    perfilAdoptante:
      "Buscamos una familia deportista o con patio grande, que tenga tiempo para entrenarla y jugar con ella.",
    tipo: "Adopción",
    publicadoPor: "Refugio Huellitas",
    imagen: "Kira.jpg",
  },
  {
    id: 4,
    nombre: "Mochi",
    especie: "Perro",
    raza: "Golden Retriever",
    edad: "2 años",
    tamanio: "Grande",
    genero: "Macho",
    salud: ["Vacunado", "Castrado"],
    personalidad: ["Activo", "Sociable"],
    apto: ["Apto niños"],
    descripcion:
      "Mochi es un amor andante. Le encanta jugar a buscar la pelota, dormir en el sofá y recibir mimos todo el día. Está vacunado, castrado y es excelente con niños.",
    perfilAdoptante:
      "Buscamos una familia con espacio al aire libre, que disfrute de paseos largos y que pueda darle todo el amor que merece.",
    tipo: "Adopción",
    publicadoPor: "Familia Torres",
    imagen: "Mochi.jpg",
  },
  {
    id: 5,
    nombre: "Oreo",
    especie: "Conejo",
    raza: "Holandés",
    edad: "2 años",
    tamanio: "Pequeño",
    genero: "Macho",
    salud: ["Desparasitado"],
    personalidad: ["Juguetón", "Sociable"],
    apto: ["Indoor", "Apto niños", "Apto otros animales"],
    descripcion:
      "Oreo es un conejo blanco y negro muy simpático. Le gusta que lo saquen a pasear en el jardín y se lleva bien con otros animales.",
    perfilAdoptante:
      "Buscamos una familia que lo deje explorar y que le dé verduras frescas y mucho cariño.",
    tipo: "Adopción",
    publicadoPor: "Valentina López",
    imagen: "oreo.jpg",
  },
  {
    id: 6,
    nombre: "Tita",
    especie: "Gato",
    raza: "Siamés",
    edad: "5 años",
    tamanio: "Pequeño",
    genero: "Hembra",
    salud: ["Vacunada", "Esterilizada", "Con pedigree"],
    personalidad: ["Tranquila", "Tímida"],
    apto: ["Indoor"],
    descripcion:
      "Tita es una gata siamesa elegante y muy independiente. Le gusta mirar por la ventana y elige con cuidado a quién darle cariño, pero cuando lo hace es para siempre.",
    perfilAdoptante:
      "Buscamos un hogar silencioso, sin muchos ruidos, con una persona paciente que respete sus tiempos.",
    tipo: "Adopción",
    publicadoPor: "Carolina Díaz",
    imagen: "Tita.jpg",
  },
  {
    id: 7,
    nombre: "Rocky",
    especie: "Perro",
    raza: "Mestizo",
    edad: "5 años",
    tamanio: "Grande",
    genero: "Macho",
    salud: ["Vacunado", "Castrado", "Desparasitado"],
    personalidad: ["Sociable", "Tranquilo"],
    apto: ["Apto niños", "Apto otros animales", "Outdoor"],
    descripcion:
      "Rocky fue rescatado de la calle y es muy agradecido. Es un perro noble, obediente y le encanta acompañar a su familia a todos lados.",
    perfilAdoptante:
      "Buscamos una familia con patio que quiera un compañero fiel y le dé una segunda oportunidad.",
    tipo: "Adopción",
    publicadoPor: "Refugio Patitas",
    imagen: "Rocky.jpg",
  },
];